mod footer_now_playing;
pub mod interface;
mod popup_add_to;
mod popup_album_info;
mod popup_connection_test;
mod popup_genre_filter;
mod popup_update;
mod tab_albums;
mod tab_home;
mod tab_playlists;
mod tab_queue;
mod utils;
mod tab_artists;
mod popup_select_playlist;
mod popup_synchronize_playlist;
mod popup_deletion_playlist;
